### ISSUE TITLE
not run

### ISSUE THREAD

**Issue by znnspace** [prolincur/three-dxf-loader#3]
TypeError: Cannot read properties of undefined (reading 'prototype')
    at Module.eval (three-dxf-loader.js?41ca:16:1)
    at t (three-dxf-loader.js?41ca:16:1)
    at eval (three-dxf-loader.js?41ca:16:1)
    at eval (three-dxf-loader.js?41ca:16:1)
    at eval (three-dxf-loader.js?41ca:16:1)
    at eval (three-dxf-loader.js?41ca:16:1)
    at Object../node_modules/three-dxf-loader/dist/three-dxf-loader.js (19.js:1291:1)
    at __webpack_require__ (app.js:854:30)
    at fn (app.js:151:20)
    at eval (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/modules/site/center-map.vue?vue&type=script&lang=js&:11:74)

**Comment by Yapacdev** [comment]
Same issue when adding three-dxf-loader while working with [threejs-webpack-starter](https://github.com/designcourse/threejs-webpack-starter) it doesnt work

**Comment by sonisourabh** [comment]
@znnspace @Yapac can you let us know which version of `three.js` are you using. Also note that we have recently upgraded `three-dxf-loader` for newer version of `three.js`

**Comment by Yapacdev** [comment]
Hi Sourabh,I actually made my own dxf loader to work with it privately, if you need more information or more people on your team I’m available to talk.YassineSent from my iPhoneOn 08/10/2023, at 08:16, Sourabh Soni ***@***.***> wrote:﻿
@znnspace @Yapac can you let us know which version of three.js are you using. Also note that we have recently upgraded three-dxf-loader for newer version of three.js
